Tipo.create(descricao: 'Débito', natureza: '0', sinal: '0')
Tipo.create(descricao: 'Boleto', natureza: '1', sinal: '1')
Tipo.create(descricao: 'Financiamento', natureza: '1', sinal: '1')
Tipo.create(descricao: 'Crédito', natureza: '0', sinal: '0')
Tipo.create(descricao: 'Recebimento', natureza: '0', sinal: '0')
Tipo.create(descricao: 'Vendas', natureza: '0', sinal: '0')
Tipo.create(descricao: 'Recebimento TED', natureza: '0', sinal: '0')
Tipo.create(descricao: 'Recebimento DOC', natureza: '0', sinal: '0')
Tipo.create(descricao: 'Aluguel', natureza: '1', sinal: '1')
