Tipo.create(descricao: 'Débito', natureza: :entrada, sinal: :positivo)
Tipo.create(descricao: 'Boleto', natureza: :saida, sinal: :negativo)
Tipo.create(descricao: 'Financiamento', natureza: :saida, sinal: :negativo)
Tipo.create(descricao: 'Crédito', natureza: :entrada, sinal: :positivo)
Tipo.create(descricao: 'Recebimento', natureza: :entrada, sinal: :positivo)
Tipo.create(descricao: 'Vendas', natureza: :entrada, sinal: :positivo)
Tipo.create(descricao: 'Recebimento TED', natureza: :entrada, sinal: :positivo)
Tipo.create(descricao: 'Recebimento DOC', natureza: :entrada, sinal: :positivo)
Tipo.create(descricao: 'Aluguel', natureza: :saida, sinal: :negativo)
